# Actions train a model on Azure Machine Learning
name: aml-train-deploy-workflow

on:
  push:
    branches:
      - dev-branch
    # paths:
    #   - 'code/*'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create/Check Azure ML Compute
      run: |
        az ml compute create --file code/compute.yml --resource-group hydra-eu-rg --workspace-name hydra-eu-ws
    
    # # Submit a training run to the Azure Machine Learning
    # - name: Submit training run
    #   id: aml_run
    #   uses: Azure/aml-run@v1
    #   with:
    #       azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Azure ML Job
      run: |
        run_id=$(az ml job create --file src/job.yml \
          --resource-group hydra-eu-rg \
          --workspace-name hydra-eu-ws \
          --query name -o tsv

    # # Register model in Azure Machine Learning model registry
    # - name: Register model
    #   id: aml_registermodel
    #   uses: Azure/aml-registermodel@v1
    #   with:
    #       azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #       run_id:  ${{ steps.aml_run.outputs.run_id }}
    #       experiment_name: ${{ steps.aml_run.outputs.experiment_name }}

    # # Deploy model in Azure Machine Learning to ACI
    # - name: Deploy model
    #   id: aml_deploy
    #   uses: Azure/aml-deploy@v1
    #   with:
    #       azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #       model_name:  ${{ steps.aml_registermodel.outputs.model_name }}
    #       model_version: ${{ steps.aml_registermodel.outputs.model_version }}
