# Actions train a model on Azure Machine Learning
name: aml-train-deploy-workflow

on:
  push:
    branches:
      - dev-branch
    # paths:
    #   - 'code/*'

jobs:
  Train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v4

    - name: Install Azure CLI and ML extension
      run: |
        az extension add -n ml -y
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # This step has to happen after logging in and the AzureCloud is set up, with this step, there's no need to specify ws and rg for every CLI command
    - name: Set Subscription and connect to workspace
      run: |
        az account set --subscription $(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)
        az configure --defaults workspace=hydra-eu-ws group=hydra-eu-rg location=eastus2
        
    - name: Create/Check Azure ML Compute
      run: |
        az ml compute create --file code/compute.yml
  
    - name: Submit Azure ML Job
      id: get_run_id  # Assign id so the output can reference this step
      run: |
        run_id=$(az ml job create --file src/job.yml \
          --query name --stream -o tsv)
        echo "run_id=$run_id" >> $GITHUB_ENV # Persist the run_id as a GitHub Actions environment variable

    - name: Register the model
      run: |
        az ml model create --name my-registered-model --type mlflow_model \
          --path runs:/${{ env.run_id }}/model/    

    # # Register model in Azure Machine Learning model registry
    # - name: Register model
    #   id: aml_registermodel
    #   uses: Azure/aml-registermodel@v1
    #   with:
    #       azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #       run_id:  ${{ steps.aml_run.outputs.run_id }}
    #       experiment_name: ${{ steps.aml_run.outputs.experiment_name }}

    # # Deploy model in Azure Machine Learning to ACI
    # - name: Deploy model
    #   id: aml_deploy
    #   uses: Azure/aml-deploy@v1
    #   with:
    #       azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #       model_name:  ${{ steps.aml_registermodel.outputs.model_name }}
    #       model_version: ${{ steps.aml_registermodel.outputs.model_version }}
